import {chromium} from "playwright";
import assert from "node:assert/strict";

const baseURL=process.env.BASE_URL??"http://localhost:3000";
const browser=await chromium.launch({headless:true,executablePath:"C:/Program Files/Google/Chrome/Application/chrome.exe"});
const context=await browser.newContext();
const page=await context.newPage();
const errors=[];
page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});
await page.goto(`${baseURL}/giris`,{waitUntil:"domcontentloaded"});
await page.locator('[name="username"]').fill("meyeka");
await page.locator('[name="password"]').fill("7472");
await page.getByRole("button",{name:"Giriş yap"}).click();
await page.waitForURL(`${baseURL}/`);
await page.goto(`${baseURL}/kategoriler`,{waitUntil:"domcontentloaded"});
await page.getByText("Satış Gelirleri",{exact:true}).waitFor();
await page.getByRole("button",{name:"Kategori ekle"}).click();
const categoryForm=page.locator("form").last();
await categoryForm.locator('[name="name"]').fill("Proje Gelirleri");
await categoryForm.locator('[name="kind"]').selectOption("income");
await categoryForm.getByRole("button",{name:"Kategoriyi kaydet"}).click();
await page.getByText("Proje Gelirleri",{exact:true}).waitFor();
await page.goto(`${baseURL}/gelirler`,{waitUntil:"domcontentloaded"});
await page.getByRole("button",{name:"Gelir ekle"}).click();
const form=page.locator("form").last();
assert.equal(await form.evaluate(element=>element.checkValidity()),false);
await form.locator('[name="name"]').fill("Profesyonel test geliri");
await form.locator('[name="amount"]').fill("25000");
await form.locator('[name="category"]').selectOption("Proje Gelirleri");
await form.locator('[name="description"]').fill("Kategori bağlantısı ve zorunlu alan testi");
await form.locator('[name="reference"]').fill("INV-2026-001");
assert.equal(await form.evaluate(element=>element.checkValidity()),true);
await form.getByRole("button",{name:"Kaydet"}).click();
await page.getByText("Profesyonel test geliri",{exact:true}).waitFor();
await page.goto(`${baseURL}/`,{waitUntil:"domcontentloaded"});
await page.getByText("Profesyonel test geliri",{exact:true}).waitFor();
assert.equal(errors.length,0,errors.join(" | "));
console.log(JSON.stringify({result:"BAŞARILI",categoryCrud:true,requiredValidation:true,recordSync:true,consoleErrors:0},null,2));
await browser.close();
