import {ArrowDownLeft,ArrowUpRight,CalendarDays,ChevronRight,Clock3,Ellipsis,Eye,TrendingDown,TrendingUp,WalletCards} from "lucide-react";
import {Shell} from "@/components/shell";import {CashChart,CategoryChart} from "@/components/charts";import {money} from "@/lib/format";import {payments,transactions} from "@/lib/data";
import {NotificationList} from "@/components/notification-center";
const stats=[
 {label:"Toplam bakiye",value:0,change:"%0",up:true,icon:WalletCards},
 {label:"Bu ay gelir",value:0,change:"%0",up:true,icon:ArrowDownLeft},
 {label:"Bu ay gider",value:0,change:"%0",up:false,icon:ArrowUpRight},
 {label:"Net nakit akışı",value:0,change:"%0",up:true,icon:TrendingUp}
];
export default function Dashboard(){return <Shell title="Günaydın, Muhammed 👋" subtitle="14 Eylül 2026, Pazartesi"><div className="mx-auto max-w-[1500px] enter">
 <section className="mb-7 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><h2 className="text-2xl font-bold tracking-[-.035em] md:text-[28px]">Finansal durumunuz</h2><p className="mt-1 text-sm text-[#777772]">Şirketinizin bugünkü finansal görünümü.</p></div><div className="flex items-center gap-2 rounded-xl border border-[#e5e3de] bg-white p-1.5 text-xs"><button className="rounded-lg bg-[#171717] px-3 py-2 font-semibold text-white">Bu ay</button><button className="px-3 py-2 text-[#73736f]">Bu çeyrek</button><button className="px-3 py-2 text-[#73736f]">Bu yıl</button></div></section>
 <section className="card mb-4 border-l-4 border-l-[#f5c400] p-5"><NotificationList/></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({label,value,change,up,icon:Icon},i)=><article key={label} className="card p-5" style={{animationDelay:`${i*50}ms`}}><div className="flex items-center justify-between"><span className="text-[13px] font-medium text-[#797974]">{label}</span><div className="grid size-9 place-items-center rounded-xl bg-[#f5f5f2]"><Icon size={18}/></div></div><div className="mt-4 flex items-end justify-between gap-2"><b className="number text-[27px]">{money(value)}</b><span className={`mb-1 flex items-center text-[11px] font-bold ${up?"text-[#15945e]":"text-[#d84b47]"}`}>{up?<TrendingUp size={13}/>:<TrendingDown size={13}/>} {change}</span></div><p className="mt-1 text-[11px] text-[#aaa9a4]">Geçen aya göre</p></article>)}</section>
 <section className="mt-4 grid gap-4 xl:grid-cols-[1.55fr_1fr]"><article className="card p-5 md:p-6"><div className="flex items-start justify-between"><div><h3 className="font-bold">Gelir / gider analizi</h3><p className="mt-1 text-xs text-[#8b8b86]">Son 6 aylık finansal hareket</p></div><div className="flex gap-4 text-[11px]"><span><i className="mr-1.5 inline-block size-2 rounded-full bg-[#f5c400]"/>Gelir</span><span><i className="mr-1.5 inline-block size-2 rounded-full bg-[#282828]"/>Gider</span></div></div><div className="mt-3"><CashChart/></div></article><article className="card p-5 md:p-6"><div className="flex justify-between"><div><h3 className="font-bold">Gider dağılımı</h3><p className="mt-1 text-xs text-[#8b8b86]">Eylül 2026</p></div><button><Ellipsis size={20}/></button></div><CategoryChart/></article></section>
 <section className="mt-4 grid gap-4 xl:grid-cols-[1fr_1.1fr]"><article className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#eeece8] p-5"><div><h3 className="font-bold">Yaklaşan ödemeler</h3><p className="mt-1 text-xs text-[#8b8b86]">Önümüzdeki 30 gün</p></div><button className="flex items-center text-xs font-semibold">Tümünü gör <ChevronRight size={15}/></button></div><div>{payments.slice(0,3).map((p,i)=><div key={p.title} className="flex items-center gap-3 border-b border-[#f0efeb] px-5 py-3.5 last:border-0"><div className="grid size-9 place-items-center rounded-xl text-xs font-bold text-white" style={{background:p.tone}}>{p.icon}</div><div><div className="text-sm font-semibold">{p.title}</div><div className="mt-0.5 text-[11px] text-[#8c8c87]">{p.category}</div></div><div className="ml-auto text-right"><div className="number text-sm font-bold">{money(p.amount)}</div><div className={`mt-0.5 text-[11px] ${i===0?"text-[#dc6f2b]":"text-[#8c8c87]"}`}>{p.date}</div></div></div>)}</div></article>
 <article className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#eeece8] p-5"><div><h3 className="font-bold">Son işlemler</h3><p className="mt-1 text-xs text-[#8b8b86]">En güncel hareketler</p></div><button className="flex items-center text-xs font-semibold">Tümünü gör <ChevronRight size={15}/></button></div><div>{transactions.slice(0,3).map(t=><div key={t.title} className="flex items-center gap-3 border-b border-[#f0efeb] px-5 py-3.5 last:border-0"><div className={`grid size-9 place-items-center rounded-xl ${t.type==="in"?"bg-[#eaf8f0] text-[#15945e]":"bg-[#fff0ee] text-[#dc514c]"}`}>{t.type==="in"?<ArrowDownLeft size={18}/>:<ArrowUpRight size={18}/>}</div><div><div className="text-sm font-semibold">{t.title}</div><div className="mt-0.5 text-[11px] text-[#8c8c87]">{t.detail} · {t.date}</div></div><div className={`number ml-auto text-sm font-bold ${t.type==="in"?"text-[#15945e]":"text-[#dc514c]"}`}>{t.type==="in"?"+":"−"}{money(t.amount)}</div></div>)}</div></article></section>
 <section className="mt-4 grid gap-4 md:grid-cols-3"><article className="card flex items-center gap-4 p-5"><div className="grid size-11 place-items-center rounded-xl bg-[#fff4e8] text-[#d9782d]"><Clock3/></div><div><div className="text-xs text-[#7b7b76]">Yaklaşan ödemeler</div><b className="number mt-1 block text-xl">0 TL</b></div></article><article className="card flex items-center gap-4 p-5"><div className="grid size-11 place-items-center rounded-xl bg-[#fff0ee] text-[#db4f49]"><CalendarDays/></div><div><div className="text-xs text-[#7b7b76]">Geciken ödemeler</div><b className="number mt-1 block text-xl">0 TL</b></div></article><article className="card relative overflow-hidden p-5"><div className="absolute right-0 top-0 h-full w-1 bg-[#f5c400]"/><div className="text-xs text-[#7b7b76]">Ay sonu tahmini bakiye</div><div className="mt-1 flex items-center gap-2"><b className="number text-xl">0 TL</b><Eye size={15} className="text-[#999]"/></div><p className="mt-1 text-[11px] text-[#777]">Henüz planlanmış hareket yok</p></article></section>
 </div></Shell>}
