"use client";
import {useEffect,useState} from "react";
import {Plus,Shapes,Trash2,X} from "lucide-react";
import {Shell} from "./shell";
import {categoryStorageKey,defaultCategories,FinanceCategory,readCategories} from "@/lib/categories";

const field="mt-1.5 h-11 w-full rounded-xl border border-[#dedbd3] bg-white px-3 text-sm outline-none focus:border-[#c5a300]";
export function CategoryManager(){
 const [items,setItems]=useState<FinanceCategory[]>(defaultCategories),[open,setOpen]=useState(false);
 useEffect(()=>setItems(readCategories()),[]);
 function persist(next:FinanceCategory[]){setItems(next);localStorage.setItem(categoryStorageKey,JSON.stringify(next));window.dispatchEvent(new Event("meyeka:categories"))}
 function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const name=String(form.get("name")).trim();const kind=String(form.get("kind")) as FinanceCategory["kind"];if(name.length<2||items.some(item=>item.kind===kind&&item.name.toLocaleLowerCase("tr-TR")===name.toLocaleLowerCase("tr-TR")))return;persist([...items,{id:crypto.randomUUID(),name,kind,color:String(form.get("color"))}]);setOpen(false)}
 return <Shell title="Kategoriler" subtitle="Gelir ve gider sınıflandırmalarını yönetin"><div className="mx-auto max-w-[1100px] enter"><div className="mb-6 flex items-end justify-between"><div><h2 className="text-2xl font-bold">Kategori yönetimi</h2><p className="mt-1 text-sm text-[#797974]">Finansal işlemlerde kullanılacak kategorileri tanımlayın.</p></div><button onClick={()=>setOpen(true)} className="flex h-10 items-center gap-2 rounded-xl bg-[#171717] px-4 text-sm font-semibold text-white"><Plus size={17}/>Kategori ekle</button></div><div className="grid gap-5 md:grid-cols-2">{(["income","expense"] as const).map(kind=><section key={kind} className="card overflow-hidden"><div className="border-b px-5 py-4"><h3 className="font-bold">{kind==="income"?"Gelir kategorileri":"Gider kategorileri"}</h3><p className="mt-1 text-xs text-[#888]">{items.filter(item=>item.kind===kind).length} kategori</p></div><div>{items.filter(item=>item.kind===kind).map(item=><div key={item.id} className="flex items-center gap-3 border-b px-5 py-3.5 last:border-0"><span className="size-3 rounded-full" style={{background:item.color}}/><span className="text-sm font-medium">{item.name}</span><button onClick={()=>persist(items.filter(category=>category.id!==item.id))} title="Kategoriyi sil" className="ml-auto rounded-lg p-2 text-[#999] hover:bg-red-50 hover:text-red-600"><Trash2 size={16}/></button></div>)}</div></section>)}</div></div>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4"><form onSubmit={submit} className="w-full max-w-[480px] rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-6 py-5"><div className="flex items-center gap-3"><Shapes/><div><h2 className="font-bold">Yeni kategori</h2><p className="text-xs text-[#888]">Benzersiz ve açıklayıcı bir ad kullanın.</p></div></div><button type="button" onClick={()=>setOpen(false)} className="rounded-lg p-2 hover:bg-[#f4f3ef]"><X size={18}/></button></div><div className="grid gap-4 p-6"><label className="text-xs font-semibold">Kategori adı<input name="name" required minLength={2} maxLength={40} className={field} placeholder="Örn. Lojistik giderleri"/></label><label className="text-xs font-semibold">Kategori türü<select name="kind" required className={field}><option value="income">Gelir</option><option value="expense">Gider</option></select></label><label className="text-xs font-semibold">Renk<input name="color" type="color" defaultValue="#f5c400" className={`${field} p-1`}/></label></div><div className="flex justify-end gap-2 border-t px-6 py-4"><button type="button" onClick={()=>setOpen(false)} className="h-10 rounded-xl border px-4 text-sm font-semibold">Vazgeç</button><button className="h-10 rounded-xl bg-[#171717] px-5 text-sm font-semibold text-white">Kategoriyi kaydet</button></div></form></div>}</Shell>
}
