"use client";
import {FileDown,FileSpreadsheet} from "lucide-react";import {jsPDF} from "jspdf";
const reportRows=[["Toplam Gelir",0],["Toplam Gider",0],["Net Nakit Akışı",0],["Bekleyen Ödemeler",0],["Geciken Ödemeler",0]] as const;
const fileDate=()=>new Date().toISOString().slice(0,10);
export function ReportExport(){
 function downloadPdf(){const pdf=new jsPDF();pdf.setFontSize(19);pdf.text("Meyeka Finans",20,22);pdf.setFontSize(12);pdf.text(`Finans Raporu - ${fileDate()}`,20,32);pdf.setDrawColor(220);pdf.line(20,38,190,38);let y=51;reportRows.forEach(([label,value])=>{pdf.setFont("helvetica","bold");pdf.text(label,20,y);pdf.setFont("helvetica","normal");pdf.text(`${value.toLocaleString("tr-TR")} TRY`,150,y,{align:"right"});y+=11});pdf.save(`meyeka-finans-raporu-${fileDate()}.pdf`)}
 function downloadExcel(){const rows=reportRows.map(([label,value])=>`<Row><Cell><Data ss:Type="String">${label}</Data></Cell><Cell><Data ss:Type="Number">${value}</Data></Cell><Cell><Data ss:Type="String">${fileDate()}</Data></Cell></Row>`).join("");const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Finans Özeti"><Table><Row><Cell><Data ss:Type="String">Kalem</Data></Cell><Cell><Data ss:Type="String">Tutar (TRY)</Data></Cell><Cell><Data ss:Type="String">Tarih</Data></Cell></Row>${rows}</Table></Worksheet></Workbook>`;const url=URL.createObjectURL(new Blob([xml],{type:"application/vnd.ms-excel;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`meyeka-finans-raporu-${fileDate()}.xls`;link.click();URL.revokeObjectURL(url)}
 return <div className="flex flex-wrap gap-2"><button onClick={downloadPdf} className="flex h-10 items-center gap-2 rounded-xl border border-[#dedbd3] bg-white px-4 text-sm font-semibold hover:bg-[#faf9f6]"><FileDown size={17}/> PDF indir</button><button onClick={downloadExcel} className="flex h-10 items-center gap-2 rounded-xl bg-[#171717] px-4 text-sm font-semibold text-white hover:bg-black"><FileSpreadsheet size={17}/> Excel indir</button></div>
}
