import {TablePage,Row} from "@/components/table-page";import {employees,payments,subscriptions,transactions} from "@/lib/data";import {Shell} from "@/components/shell";import {CategoryChart,CashChart} from "@/components/charts";import {money} from "@/lib/format";import {ChevronLeft,ChevronRight} from "lucide-react";import {ReportExport} from "@/components/report-export";
const income:Row[]=transactions.filter(x=>x.type==="in").map(x=>({name:x.title,detail:x.detail,date:x.date,amount:x.amount,status:"Ödendi",type:"in"}));
const expense:Row[]=transactions.filter(x=>x.type==="out").map(x=>({name:x.title,detail:x.detail,date:x.date,amount:x.amount,status:"Ödendi",type:"out"}));
const Empty=({text}:{text:string})=><div className="py-12 text-center text-sm text-[#888]">{text}</div>;
function Mini({label,value}:{label:string,value:string}){return <div className="card p-5"><div className="text-xs text-[#777]">{label}</div><b className="number mt-2 block text-2xl">{value}</b></div>}
function Personnel(){return <Shell title="Personel" subtitle="Çalışan ve maliyet yönetimi" action="Personel ekle"><div className="mx-auto max-w-[1500px] enter"><div className="mb-5 grid gap-4 md:grid-cols-3"><Mini label="Aktif personel" value="0"/><Mini label="Aylık maaş toplamı" value="0 TL"/><Mini label="Toplam personel maliyeti" value="0 TL"/></div><div className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Personel maliyetleri</h2></div>{employees.length===0?<Empty text="Henüz personel kaydı bulunmuyor."/>:<div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><tbody>{employees.map(e=><tr key={e.name}><td>{e.name}</td><td>{money(e.salary)}</td></tr>)}</tbody></table></div>}</div></div></Shell>}
function Subs(){return <TablePage title="Abonelikler" subtitle="Tekrarlayan ödemelerinizi yönetin" action="Abonelik ekle" rows={subscriptions.map(s=>({name:s.name,detail:`${s.company} · ${s.period}`,date:s.renewal,amount:s.amount,status:"Aktif"}))}/>}
function Calendar(){const days=Array.from({length:35},(_,i)=>i-1);return <Shell title="Finansal Takvim" subtitle="Eylül 2026" action="Etkinlik ekle"><div className="mx-auto max-w-[1300px] enter"><div className="card overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div className="flex gap-2"><button className="rounded-lg border p-2"><ChevronLeft size={17}/></button><button className="rounded-lg border p-2"><ChevronRight size={17}/></button><b className="ml-3 self-center">Eylül 2026</b></div><div className="rounded-xl bg-[#f3f2ef] p-1 text-xs"><button className="rounded-lg bg-white px-3 py-2 shadow-sm">Ay</button><button className="px-3 py-2">Hafta</button><button className="px-3 py-2">Gün</button></div></div><div className="grid grid-cols-7 bg-[#fafaf8] text-center text-xs text-[#888]">{["Pzt","Sal","Çar","Per","Cum","Cmt","Paz"].map(d=><div className="border-b p-3" key={d}>{d}</div>)}</div><div className="grid grid-cols-7">{days.map((d,i)=><div key={i} className="min-h-24 border-b border-r p-2 text-xs sm:min-h-28"><span className={d===14?"grid size-6 place-items-center rounded-full bg-[#f5c400] font-bold":"text-[#777]"}>{d>0&&d<=30?d:""}</span></div>)}</div></div></div></Shell>}
function Reports(){return <Shell title="Raporlar" subtitle="Finansal performans ve analizler"><div className="mx-auto max-w-[1400px] enter"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Finans raporu</h2><p className="mt-1 text-xs text-[#888]">PDF veya Excel formatında dışa aktarın.</p></div><ReportExport/></div><div className="mb-4 grid gap-4 md:grid-cols-4"><Mini label="Toplam gelir" value="0 TL"/><Mini label="Toplam gider" value="0 TL"/><Mini label="Net kâr" value="0 TL"/><Mini label="Kâr marjı" value="%0"/></div><div className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="card p-6"><h3 className="font-bold">Aylık finansal trend</h3><div className="mt-5"><CashChart/></div></div><div className="card p-6"><h3 className="font-bold">Kategori analizi</h3><CategoryChart/></div></div></div></Shell>}
function Generic({name}:{name:string}){const labels:Record<string,string>={kategoriler:"Kategoriler"};const title=labels[name]??"Sayfa";return <Shell title={title} subtitle="Finans yönetimi"><div className="mx-auto max-w-[1000px] enter"><div className="card p-6"><h2 className="text-xl font-bold">{title}</h2><Empty text="Henüz kayıt bulunmuyor."/></div></div></Shell>}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const name=slug[0];if(name==="gelirler")return <TablePage title="Gelirler" subtitle="Tahsilat ve gelir yönetimi" action="Gelir ekle" rows={income}/>;if(name==="giderler")return <TablePage title="Giderler" subtitle="Tüm şirket harcamaları" action="Gider ekle" rows={expense}/>;if(name==="odemeler")return <TablePage title="Ödemeler" subtitle="Yaklaşan ve tamamlanan ödemeler" action="Ödeme planla" rows={payments.map(p=>({name:p.title,detail:p.category,date:p.date,amount:p.amount,status:"Bekliyor"}))}/>;if(name==="personel")return <Personnel/>;if(name==="abonelikler")return <Subs/>;if(name==="takvim")return <Calendar/>;if(name==="raporlar")return <Reports/>;return <Generic name={name}/>}
